name: GitHub Pages # 定义 GitHub Actions 工作流的名称


on:
  push:
    branches:
      - master  # 监听的分支，如有需要可修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          submodules: true  # 递归检出子模块（主题）
          fetch-depth: 0         # 获取完整的提交历史

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Hugo 主题可能需要 Node.js

      - name: 安装 Dart Sass
        run: sudo apt-get install dart-sass

      - name: 安装 Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: 构建站点 # 构建 Hugo 静态网站
        run: hugo --minify # 运行 Hugo 构建命令，并使用 --minify 选项来压缩生成的文件

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
